name: 'pytest'

on:
  push:
    branches: '*'

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          cargo build --release
          cd python
          cargo build --release
          pip install .
      - name: Test with pytest
        run: |
          cd python/rustylasso/tests
          pytest
