[package]
name = "RustyLasso"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.4"
num = "0.4.0"
rand = "0.8.4"
rand_distr = "0.4.2"
