[build-system]
requires = [
    "setuptools",
    "wheel",
    "setuptools-rust",
    "numpy==1.13.3; python_version=='3.6'",
    "numpy==1.14.5; python_version=='3.7'",
    "numpy==1.17.3; python_version>='3.8'"
]
