name: Publish
on:
  release:
    types: [published]

jobs:
  publish-on-crates-io-server:
    name: Publish on crates.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to crates.io
        run: cargo login -t ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish to crates.io
        run: cargo publish
